name: "Deploy function"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      tf_vars:
        required: false
        type: string

jobs: 
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_project_number: ${{ secrets.GCP_PROJECT_NUMBER }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}
      TF_VAR_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create Source Zip
        run: |
          cd ${{ inputs.name }}/function
          zip -r ../source.zip .

      - name: Terraform Init/Plan/Apply
        working-directory: ${{ inputs.name }}
        run: |
          terraform init
          terraform plan -input=false ${{ inputs.tf_vars }}
          terraform apply -auto-approve -input=false ${{ inputs.tf_vars }}